/************************************************************************** 

      Copyright (c) Branson Ultrasonics Corporation, 1996-2021
 
     This program is the property of Branson Ultrasonics Corporation
     Copying of this software is expressly forbidden, without the prior
     written consent of Branson Ultrasonics Corporation.
     
---------------------------- MODULE DESCRIPTION ----------------------------
 
 All the definition that need to be used both on ASC and HMI software should be in here.  
 
***************************************************************************/

#ifndef SHARED_COMMON_H_
#define SHARED_COMMON_H_
enum RequestIdentities
{
	SCBL_HEART_BEAT_REQ							= 0,
	SCBL_USER_DETAILS_READ_REQ,
	SCBL_PASSCODE_VALIDATE_REQ,
	SCBL_ACTIVE_RECIPE_BASIC_INFO_READ_REQ,
	SCBL_WELD_RECIPE_LIST_READ_REQ,
	SCBL_SYSINFO_READ_REQ,
	SCBL_WELDRECIPE_REQ,
	SCBL_GRAPH_READ_REQ,
	SCBL_RECIPE_LIBRARY_READ_REQ,
	SCBL_GET_RECIPE_INFO_READ_REQ,
	SCBL_CREATE_NEW_RECIPE_READ_REQ,
	SCBL_INSERT_RECIPE_READ_REQ,
	SCBL_UPDATE_RECIPE_READ_REQ,
	SCBL_DELETE_RECIPE_READ_REQ,
	SCBL_SET_ACTIVE_RECIPE_READ_REQ,
	SCBL_SETUP_WELD_PARAM_WRITE_REQ,
	SCBL_SETUP_QUALITY_PARAM_WRITE_REQ,
	SCBL_SETUP_ADVANCED_PARAM_WRITE_REQ,
	SCBL_ACTIVE_RECIPE_VALIDATE_REQ,
	SCBL_TEACH_RECIPE_READ_REQ,
	SCBL_TEACH_RECIPE_INITIAL_REQ,
	SCBL_TEAHMODE_RECIPE_VALIDATE_REQ,
	SCBL_TEACH_RECIPE_ACCEPT_REQ,
	SCBL_ALARM_RESET_READ_REQ,
	SCBL_GET_PERMISSION_SCREEN_REQ,
	SCBL_SET_PERMISSION_SCREEN_REQ,
	SCBL_GET_PASSCODE_LIST_REQ,
	SCBL_UPDATE_PASSCODE_REQ,
	SCBL_SYSCONFIG_READ_REQ,
	SCBL_SYSCONFIG_WRITE_REQ,
	SCBL_INITIALIZATION_REQ,
    SCBL_HEIGHT_CALIBRATE_CHECK_REQ,
    SCBL_HEIGHT_CALIBRATE_START_REQ,
    SCBL_HEIGHT_CALIBRATE_CORRECT_REQ,
    SCBL_HEIGHT_CALIBRATE_ACCEPT_REQ,
	DUMMY
};

enum SCREENINDEX
{
    DASHBORD_SCREEN = 0,
    MENU_OPTIONS_SCREEN,
    RECIPE_MENU_SCREEN,
    RECIPE_LIBRARY_SCREEN,
    NEW_RECIPE_SCREEN,
    EDIT_RECIPE_SCREEN,
    SEQUENCE_LIBRARY_SCREEN,
    NEW_SEQUENCE_SCREEN,
    EDIT_SEQUENCE_SCREEN,
    MAINTAIN_SCREEN,
    MAINTAIN_ACTUATOR_SCREEN,
    MAINTAIN_SONICS_SCREEN,
    MAINTAIN_COUNTERS_SCREEN,
    SYSTEM_CONFIG_SCREEN,
    CONFIG_WELD_DEFAULT_SCREEN,
    CONFIG_LANGUAGE_SCREEN,
    CONFIG_UNIT_SCREEN,
    CONFIG_TEACH_MODE_SCREEN,
    CONFIG_INIT_SCREEN,
    CONFIG_POWER_SUPPLY_SCREEN,
    CONFIG_SYSTEM_TIME_SCREEN,
    ADMINISTRATOR_SCREEN,
    PASSCODE_LIST_SCREEN,
    PERMISSON_SETTING_SCREEN,
    DATA_LOG_SCREEN,
    WELD_RESULT_HISTORY_SCREEN,
    WELD_RESULT_GRAPH_SCREEN,
    ALARM_LOG_SCREEN,
    CONNECTIVITY_SCREEN,
    ETHERNET_SCREEN,
    GATEWAY_DATA_SCREEN,
    GATEWAY_MACHIEN_IP_SCREEN,
    USER_IO_SCREEN,
    DATA_EXPORT_SCREEN,
    CALIBRATION_SCREEN,
    HEIGHT_CALIBRATION_SCREEN,
    AMPLITUDE_CALIBRATINON_SCREEN,
    SYSTEM_INFORMATION_SCREEN,
    SYSTEMINFO_UPGRADE,
    SETUP_TEACH_SCREEN,
    SETUP_SCREEN,
    TEACH_MODE_SCREEN,
    KEYBOARD_SCREEN,
    PROMPT_MESSAGE_SCREEN,
    SCREEN_END
};

struct HEARTBEAT
{
	unsigned int 	CycleCounter;
	unsigned int 	RecipeNumber;
	unsigned int	AlarmCode;
	unsigned int 	TotalEnergy;
	unsigned int 	TriggerPress;
	unsigned int 	WeldPress;
	unsigned int 	Amplitude;
	unsigned int 	WeldTime;
	unsigned int 	PeakPower;
	unsigned int 	PreHeight;
	unsigned int	PostHeight;
};

#endif
