/**************************************************************************

      Copyright (c) Branson Ultrasonics Corporation, 1996-2022

     This program is the property of Branson Ultrasonics Corporation
     Copying of this software is expressly forbidden, without the prior
     written consent of Branson Ultrasonics Corporation.

---------------------------- MODULE DESCRIPTION ----------------------------

This file is to define all the commands that is used to request or response
the data between SC and HMI.

***************************************************************************/

#ifndef REQUEST_COMMAND_COMMON_H_
#define REQUEST_COMMAND_COMMON_H_
enum RequestIdentities
{
	SCBL_HEART_BEAT_REQ							= 0,
	SCBL_USER_DETAILS_READ_REQ,
	SCBL_PASSCODE_VALIDATE_REQ,
	SCBL_ACTIVE_RECIPE_BASIC_INFO_READ_REQ,
	SCBL_WELD_RECIPE_LIST_READ_REQ,
	SCBL_SYSINFO_READ_REQ,
	SCBL_WELDRECIPE_REQ,
	SCBL_GRAPH_READ_REQ,
	SCBL_RECIPE_LIBRARY_READ_REQ,
	SCBL_RECIPE_LIBRARY_NEXT_PAGE_READ_REQ,
	SCBL_GET_SELECTED_RECIPE_INFO_REQ,
	SCBL_DEFAULT_RECIPE_REQ,
	SCBL_INSERT_RECIPE_WRITE_REQ,
	SCBL_UPDATE_RECIPE_REQ,
	SCBL_DELETE_RECIPE_REQ,
	SCBL_SET_ACTIVE_RECIPE_REQ,
	SCBL_SETUP_WELD_PARAM_WRITE_REQ,
	SCBL_SETUP_QUALITY_PARAM_WRITE_REQ,
	SCBL_SETUP_ADVANCED_PARAM_WRITE_REQ,
	SCBL_ACTIVE_RECIPE_VALIDATE_REQ,
	SCBL_TEACH_RECIPE_READ_REQ,
	SCBL_TEACH_RECIPE_INITIAL_REQ,
	SCBL_TEAHMODE_RECIPE_VALIDATE_REQ,
	SCBL_TEACH_RECIPE_ACCEPT_REQ,
	SCBL_ALARM_RESET_READ_REQ,
	SCBL_GET_PERMISSION_SCREEN_REQ,
	SCBL_SET_PERMISSION_SCREEN_REQ,
	SCBL_GET_PASSCODE_LIST_REQ,
	SCBL_UPDATE_PASSCODE_REQ,
	SCBL_SYSCONFIG_READ_REQ,
	SCBL_SYSCONFIG_WRITE_REQ,
	SCBL_INITIALIZATION_REQ,
    SCBL_HEIGHT_CALIBRATE_CHECK_REQ,
    SCBL_HEIGHT_CALIBRATE_START_REQ,
    SCBL_HEIGHT_CALIBRATE_CORRECT_REQ,
    SCBL_HEIGHT_CALIBRATE_ACCEPT_REQ,
    SCBL_MAINTAIN_ACTUATOR_REQ,
    SCBL_MAINTAIN_SONICS_TEST_REQ,
    SCBL_MAINTAIN_SONICS_100TEST_REQ,
    SCBL_MAINTAIN_SONICS_RESET_REQ,
    SCBL_DATA_EXPORT_REQ,
	SCBL_RECIPE_ERROR_CODE_REQ,
	SCBL_USER_IO_INPUT_REQ,
	SCBL_DETECT_SC_USB_DEVICE_REQ,   
	SCBL_EXCUTE_FIRMWARE_UPGRADE_FROM_USB_REQ,
	DUMMY
};

enum USBdetectStatus
{
	USB_DETECT_FAIL = 0,
	USB_DETECT_SUCCESS
};

enum FirmwareUpgradeErrorCode
{
	FAILED_TO_OPEN_USB = 11,                               
	FAILED_TO_OPEN_FIRMWARE_FILE,                         
	FAILED_TO_READ_VXWORKS_FILES_FROM_USB,                
	FAILED_TO_OPEN_VXWORKS_FILE,                         
	SC_FILE_SIZE_IS_ZERO                          
};

enum SCProgressResponseToUI
{
	SC_PROGRESS_ONE = 21,
	SC_PROGRESS_TWO,
	SC_PROGRESS_THREE,
	SC_PROGRESS_FOUR,
	SC_PROGRESS_FIVE	
};

#endif
