#include<stdio.h>

#define  SYTEM_LOGIN			"SystemLogin"
#define  SYSTEM_LOGOUT			"SystemLogout"
#define  SW_VERSION				"GetSoftwareVersion"
#define  LAST_WELD				"GetWeldResult"
#define  SET_RECIPE_VALUE		"SetRecipeValue"
#define  GET_RECIPE_VALUE		"GetRecipeParamValue"
#define  GET_SYSTEM_VALUE		"GetSystemConfigValue"
#define  SAVE_RECIPE			"SaveCurrentRecipe"
#define  SET_ACTIVE_RECIPE		"SetActiveRecipe"
#define  DELETE_RECIPE			"DeleteRecipe"
#define  GET_NUM_WELD_HISTORY	"GetNumWeldData"
#define  GET_WELD_HISTORY		"GetWeldHistory"
#define  GET_NUM_ALARMS			"GetNumAlarms"
#define	 GET_ALARM_LOG			"GetAlarmLogData"
#define  GET_GRAPH_RESULT		"GetGraphResult"
#define  FIRMWARE_UPGRADE		"index.html"

typedef enum
{
	TO_WEB_SERVICES_TASK_LOGIN = 1,
	TO_WEBCLI_KERNEL_LOGIN,

	TO_WEB_SERVICES_TASK_LOGOUT,
	TO_WEBCLI_KERNEL_LOGOUT,

	TO_WEB_SERVICES_TASK_SW_VERSION,
	TO_WEBCLI_KERNEL_SW_VERSION,

	TO_WEB_SERVICES_TASK_LAST_WELD,
	TO_WEBCLI_KERNEL_LAST_WELD,

	TO_WEB_SERVICES_TASK_SET_RECIPE_VALUE,
	TO_WEBCLI_KERNEL_SET_RECIPE_VALUE,

	TO_WEB_SERVICES_TASK_GET_RECIPE_VALUE,
	TO_WEBCLI_KERNEL_GET_RECIPE_VALUE,

	TO_WEB_SERVICES_TASK_GET_SYSTEM_VALUE,
	TO_WEBCLI_KERNEL_GET_SYSTEM_VALUE,

	TO_WEB_SERVICES_TASK_SAVE_RECIPE,
	TO_WEBCLI_KERNEL_SAVE_RECIPE,

	TO_WEB_SERVICES_TASK_SET_ACTIVE_RECIPE,
	TO_WEBCLI_KERNEL_SET_ACTIVE_RECIPE,

	TO_WEB_SERVICES_TASK_DELETE_RECIPE,
	TO_WEBCLI_KERNEL_DELETE_RECIPE,

	TO_WEB_SERVICES_TASK_GET_NUM_WELD_HISTROY,
	TO_WEBCLI_KERNEL_GET_NUM_WELD_HISTROY,

	TO_WEB_SERVICES_TASK_GET_WELD_HISTROY,
	TO_WEBCLI_KERNEL_GET_WELD_HISTROY_NEXT,
	TO_WEBCLI_KERNEL_GET_WELD_HISTROY_FINISH,

	TO_WEB_SERVICES_TASK_GET_NUM_ALARMS,
	TO_WEBCLI_KERNEL_GET_NUM_ALARMS,

	TO_WEB_SERVICES_TASK_GET_ALARM_LOG,
	TO_WEBCLI_KERNEL_GET_ALARM_LOG_NEXT,
	TO_WEBCLI_KERNEL_GET_ALARM_LOG_FINISH,

	TO_WEB_SERVICES_TASK_GET_GRAPH_RESULT,
	TO_WEBCLI_KERNEL_GET_GRAPH_RESULT_NEXT,
	TO_WEBCLI_KERNEL_GET_GRAPH_RESULT_FINISH,

	TO_WEB_SERVICES_TASK_GET_RUNTIME_DETAILS,
	TO_WEBCLI_KERNEL_GET_RUNTIME_DETAILS,
	
	TO_WEB_SERVICES_TASK_GET_ALL_USER_DETAILS_FU,
	TO_WEBCLI_KERNEL_GET_ALL_USER_DETAILS_FU

}WEBSERVICES_COMMUNICATION_IDS;
