# Makefile - Custom system call definition layer Makefile
#
# Copyright 2013, 2016 Wind River Systems, Inc.
#      
# The right to copy, distribute, modify or otherwise make use
# of this software may be licensed only pursuant to the terms
# of an applicable Wind River license agreement.
#
# modification history
# -------------------- 
# 12jan16,mze  use new macros
# 01oct13,pad  created


KERNEL_PUBLIC_H_DIRS = syscall_defs
USER_PUBLIC_H_DIRS = user_h
PRE_BUILD_DIRS = pre_src
BUILD_DIRS = kernel_src

include $(WIND_KRNL_MK)/rules.layers.mk

